Executing: stoq dbadmin updateschema -v -d stoq -H localhost -p 5432 -u stoq

02:36:30 stoqlib.database.settings Connecting to postgres://stoq@localhost:5432/stoq?isolation=read-committed

02:36:30 stoqlib.database.migration Upgrading database (plugins=True, backup=True)

02:36:30 stoqlib.database.migration Locking database

02:36:30 stoqlib.database.migration Releasing database lock

02:36:30 stoqlib.database.settings Testing database connectivity using command line tools

02:36:30 stoqlib.database.settings executing psql -n -q -w --variable ON_ERROR_STOP= -c SELECT 1; -U stoq -h localhost -p 5432 stoq

02:36:31 stoqlib.database.migration Making a backup to /tmp/stoq-dump-xg2opzyd

02:36:31 stoqlib.database.create BACKUP-START:

02:36:31 stoqlib.database.settings Dumping database to /tmp/stoq-dump-xg2opzyd

02:36:31 stoqlib.database.settings executing pg_dump --format=custom --encoding=UTF-8 -f /tmp/stoq-dump-xg2opzyd -U stoq -h localhost -p 5432 stoq

02:36:43 stoqlib.lib.pluginmanager Eggs cache created in /tmp/stoqzojcn573eggs

02:36:43 stoqlib.database.migration Updating schema

02:36:43 stoqlib.database.settings Connecting to postgres://stoq@localhost:5432/stoq?isolation=read-committed

02:36:44 stoqlib.database.settings Executing SQL script /tmp/stoqfunctions-tmwhs6ka database locked=False

02:36:44 stoqlib.database.settings executing psql -U stoq -h localhost -p 5432 -n -q -f - --variable ON_ERROR_STOP= stoq

02:36:44 stoqlib.database.migration Applying 11 patches

02:36:44 stoqlib.database.create PATCHES:11

02:36:44 stoqlib.database.create PATCH:6.1

02:36:44 stoqlib.database.settings Executing SQL script /tmp/patch-6-1-oc400v1h database locked=False

02:36:44 stoqlib.database.settings executing psql -U stoq -h localhost -p 5432 -n -q -f - --variable ON_ERROR_STOP= stoq

02:36:44 stoqlib.database.create PATCH:6.2

02:36:44 stoqlib.database.settings Executing SQL script /tmp/patch-6-2-5bosnxo8 database locked=False

02:36:44 stoqlib.database.settings executing psql -U stoq -h localhost -p 5432 -n -q -f - --variable ON_ERROR_STOP= stoq

Traceback (most recent call last):

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 439, in update

    super(StoqlibSchemaMigration, self).update()

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 313, in update

    from_, to = self._update_schema()

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 235, in _update_schema

    patch.apply(self.default_store)

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 114, in apply

    retcode = db_settings.execute_sql(temporary)

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/settings.py", line 590, in execute_sql

    raise SQLError(stderr[:-1].decode())

stoqlib.database.exceptions.SQLError: psql:<stdin>:113: ERROR:  constraint "quote_group_identifier_branch_id_key" of relation "quote_group" does not exist

02:37:11 stoqlib.lib.crashreport.CustomRavenClient Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7f11e5022c88>

02:37:11 stoqlib.lib.crashreport.CustomRavenClient Sending message of length 2998 to https://sentry.stoq.com.br/api/4/store/

02:37:11 stoqlib.database.create ERROR:Traceback (most recent call last):

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 439, in update

    super(StoqlibSchemaMigration, self).update()

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 313, in update

    from_, to = self._update_schema()

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 235, in _update_schema

    patch.apply(self.default_store)

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/migration.py", line 114, in apply

    retcode = db_settings.execute_sql(temporary)

  File "/usr/lib/python3.5/dist-packages/stoqlib/database/settings.py", line 590, in execute_sql

    raise SQLError(stderr[:-1].decode())

stoqlib.database.exceptions.SQLError: psql:<stdin>:113: ERROR:  constraint "quote_group_identifier_branch_id_key" of relation "quote_group" does not exist



02:37:11 stoqlib.database.migration Restoring backup /tmp/stoq-dump-xg2opzyd

02:37:11 stoqlib.database.create RESTORE-START:

02:37:11 stoqlib.database.settings Restoring database stoq using /tmp/stoq-dump-xg2opzyd

02:37:11 stoqlib.database.settings Cleaning database stoq__backup_20191215_0237

02:37:11 stoqlib.database.settings Connecting to postgres://stoq@localhost:5432/postgres?isolation=read-committed

02:37:11 stoqlib.database.settings Connecting to postgres://stoq@localhost:5432/postgres?isolation=read-committed

02:37:11 stoqlib.database.settings Dropped database stoq__backup_20191215_0237

02:37:11 stoqlib.database.settings Connecting to postgres://stoq@localhost:5432/postgres?isolation=read-committed

02:37:13 stoqlib.database.settings executing pg_restore -d stoq__backup_20191215_0237 -U stoq -h localhost -p 5432 /tmp/stoq-dump-xg2opzyd

02:37:13 stoqlib.database.create RESTORE-DONE:stoq__backup_20191215_0237
